version: "3"

services:
  mynode:
    build: ./mynode
    container_name: mynode
    restart: always
    ports:
      - 80:80
    volumes:
      - ./mynode:/data/mynode
    # depends_on:
    #   - myredis
