version: "3"

services:
  myredis:
    container_name: myredis
    image: redis:latest
    restart: always
    # hostname: myredis
    # network_mode: host
    ports:
      - 6379:6379
    volumes:
      - ./myredis/data:/data
      - ./myredis/redis.conf:/etc/redis/redis.conf
      # - ./myredis/users.acl:/etc/redis/users.acl
    command: redis-server /etc/redis/redis.conf
